# Generated by Django 5.1.2 on 2024-12-07 23:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderDate', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('delivered', 'Delivered'), ('refunded', 'Refunded'), ('pending', 'Order Pending'), ('route', 'On Route')], default='pending', max_length=50)),
                ('totalAmount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('paymentMethod', models.CharField(choices=[('credit', 'Credit card'), ('paypal', 'Paypal'), ('debit', 'Debit card')], default='credit', max_length=50)),
                ('trackingInfo', models.CharField(max_length=200)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(choices=[('cozy', 'Cozy & Comfortable Hats'), ('seasonal', 'Seasonal Hats'), ('themed', 'Themed Hats'), ('summer', 'Summer Hats'), ('occasional', 'Occasional Hats')], default='hats', max_length=50)),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='ecommerceapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50)),
                ('colour', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('stocklevel', models.PositiveIntegerField()),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productvariant', to='ecommerceapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('priceAtPurchase', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('orderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderitem', to='ecommerceapp.order')),
                ('variantID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderitem', to='ecommerceapp.productvariant')),
            ],
        ),
        migrations.CreateModel(
            name='ImagePath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagepath', models.ImageField(blank=True, upload_to='uploads/product-images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('productVariantID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagepath', to='ecommerceapp.productvariant')),
            ],
        ),
        migrations.CreateModel(
            name='BasketItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('basketID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basketitem', to='ecommerceapp.basket')),
                ('variantID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basketitem', to='ecommerceapp.productvariant')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('reviewDate', models.DateTimeField(auto_now_add=True)),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='ecommerceapp.product')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('houseNumber', models.IntegerField()),
                ('street', models.CharField(max_length=50)),
                ('postcode', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=10)),
                ('apartmentNumber', models.IntegerField()),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='useraddress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
