# Generated by Django 5.1.2 on 2024-12-07 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paymentMethod',
            field=models.CharField(choices=[('debit', 'Debit card'), ('credit', 'Credit card'), ('paypal', 'Paypal')], default='credit', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Order Pending'), ('delivered', 'Delivered'), ('route', 'On Route'), ('refunded', 'Refunded')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='productcategories',
            name='categories',
            field=models.CharField(choices=[('occasional', 'Occasional Hats'), ('themed', 'Themed Hats'), ('summer', 'Summer Hats'), ('cozy', 'Cozy & Comfortable Hats'), ('seasonal', 'Seasonal Hats')], default='hats', max_length=50),
        ),
    ]
