# Generated by Django 5.1.2 on 2024-11-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('delivered', 'Delivered'), ('route', 'On Route'), ('refunded', 'Refunded'), ('pending', 'Order Pending')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='productcategories',
            name='categories',
            field=models.CharField(choices=[('sunglasses', 'Sunglasses'), ('hats', 'Hats')], default='hats', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='permissions',
            field=models.CharField(choices=[('admin', 'Admin-User'), ('customer', 'Customer')], default='customer', max_length=50),
        ),
    ]
