# Generated by Django 5.1.2 on 2024-12-07 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0002_alter_order_paymentmethod_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('delivered', 'Delivered'), ('refunded', 'Refunded'), ('pending', 'Order Pending'), ('route', 'On Route')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='productcategories',
            name='categories',
            field=models.CharField(choices=[('themed', 'Themed Hats'), ('cozy', 'Cozy & Comfortable Hats'), ('occasional', 'Occasional Hats'), ('summer', 'Summer Hats'), ('seasonal', 'Seasonal Hats')], default='hats', max_length=50),
        ),
    ]
