# Generated by Django 5.1.2 on 2024-11-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0002_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('route', 'On Route'), ('pending', 'Order Pending'), ('refunded', 'Refunded'), ('delivered', 'Delivered')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='productcategories',
            name='categories',
            field=models.CharField(choices=[('hats', 'Hats'), ('sunglasses', 'Sunglasses')], default='hats', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='permissions',
            field=models.CharField(choices=[('customer', 'Customer'), ('admin', 'Admin-User')], default='customer', max_length=50),
        ),
    ]
