# Generated by Django 5.1.2 on 2024-12-07 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0005_alter_order_paymentmethod_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paymentMethod',
            field=models.CharField(choices=[('credit', 'Credit card'), ('paypal', 'Paypal'), ('debit', 'Debit card')], default='credit', max_length=50),
        ),
        migrations.AlterField(
            model_name='productcategories',
            name='categories',
            field=models.CharField(choices=[('cozy', 'Cozy & Comfortable Hats'), ('summer', 'Summer Hats'), ('occasional', 'Occasional Hats'), ('themed', 'Themed Hats'), ('seasonal', 'Seasonal Hats')], default='hats', max_length=50),
        ),
    ]
