# Generated by Django 5.1.2 on 2024-12-02 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0008_contacttable_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('refunded', 'Refunded'), ('route', 'On Route'), ('delivered', 'Delivered'), ('pending', 'Order Pending')], default='pending', max_length=50),
        ),
    ]
