# Generated by Django 5.1.2 on 2024-12-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0008_alter_order_paymentmethod_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paymentMethod',
            field=models.CharField(choices=[('paypal', 'Paypal'), ('debit', 'Debit card'), ('credit', 'Credit card')], default='credit', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('delivered', 'Delivered'), ('refunded', 'Refunded'), ('route', 'On Route'), ('pending', 'Order Pending')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='productcategories',
            name='categories',
            field=models.CharField(choices=[('seasonal', 'Seasonal Hats'), ('summer', 'Summer Hats'), ('cozy', 'Cozy & Comfortable Hats'), ('themed', 'Themed Hats'), ('occasional', 'Occasional Hats')], default='hats', max_length=50),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='apartmentNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
