# Generated by Django 5.1.2 on 2025-03-22 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0009_alter_order_paymentmethod_alter_order_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('flat', 'Flat Amount'), ('percentage', 'Percentage')], max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expiry_date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='paymentMethod',
            field=models.CharField(choices=[('credit', 'Credit card'), ('paypal', 'Paypal'), ('debit', 'Debit card')], default='credit', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('route', 'On Route'), ('refunded', 'Refunded'), ('pending', 'Order Pending'), ('delivered', 'Delivered')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='productcategories',
            name='categories',
            field=models.CharField(choices=[('summer', 'Summer Hats'), ('seasonal', 'Seasonal Hats'), ('themed', 'Themed Hats'), ('occasional', 'Occasional Hats'), ('cozy', 'Cozy & Comfortable Hats')], default='hats', max_length=50),
        ),
        migrations.CreateModel(
            name='Wishlists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Wishlist #', max_length=50)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishList', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
