# Generated by Django 5.1.2 on 2025-03-18 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0009_alter_order_paymentmethod_alter_order_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketitem',
            name='quantity',
        ),
        migrations.AddField(
            model_name='basketitem',
            name='productID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to='ecommerceapp.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='basketitem',
            name='basketID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishListItem', to='ecommerceapp.basket'),
        ),
        migrations.AlterField(
            model_name='basketitem',
            name='variantID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishListItem', to='ecommerceapp.productvariant'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paymentMethod',
            field=models.CharField(choices=[('paypal', 'Paypal'), ('credit', 'Credit card'), ('debit', 'Debit card')], default='credit', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('delivered', 'Delivered'), ('route', 'On Route'), ('pending', 'Order Pending'), ('refunded', 'Refunded')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='productcategories',
            name='categories',
            field=models.CharField(choices=[('seasonal', 'Seasonal Hats'), ('themed', 'Themed Hats'), ('summer', 'Summer Hats'), ('cozy', 'Cozy & Comfortable Hats'), ('occasional', 'Occasional Hats')], default='hats', max_length=50),
        ),
        migrations.CreateModel(
            name='Wishlists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Wishlist #', max_length=50)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishList', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
