# Generated by Django 5.1.2 on 2025-03-12 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0009_alter_order_paymentmethod_alter_order_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paymentMethod',
            field=models.CharField(choices=[('credit', 'Credit card'), ('debit', 'Debit card'), ('paypal', 'Paypal')], default='credit', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Order Pending'), ('refunded', 'Refunded'), ('route', 'On Route'), ('delivered', 'Delivered')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='productcategories',
            name='categories',
            field=models.CharField(choices=[('themed', 'Themed Hats'), ('summer', 'Summer Hats'), ('seasonal', 'Seasonal Hats'), ('occasional', 'Occasional Hats'), ('cozy', 'Cozy & Comfortable Hats')], default='hats', max_length=50),
        ),
        migrations.CreateModel(
            name='wishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basketID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishListItem', to='ecommerceapp.basket')),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to='ecommerceapp.product')),
                ('variantID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishListItem', to='ecommerceapp.productvariant')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Wishlist #', max_length=50)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishList', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
