# Generated by Django 5.1.2 on 2025-03-16 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0010_alter_order_paymentmethod_alter_order_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistitem',
            name='basketID',
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='wishlistID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='wishListItem', to='ecommerceapp.wishlists'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='paymentMethod',
            field=models.CharField(choices=[('debit', 'Debit card'), ('credit', 'Credit card'), ('paypal', 'Paypal')], default='credit', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Order Pending'), ('refunded', 'Refunded'), ('delivered', 'Delivered'), ('route', 'On Route')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='productcategories',
            name='categories',
            field=models.CharField(choices=[('seasonal', 'Seasonal Hats'), ('occasional', 'Occasional Hats'), ('cozy', 'Cozy & Comfortable Hats'), ('summer', 'Summer Hats'), ('themed', 'Themed Hats')], default='hats', max_length=50),
        ),
    ]
