# Generated by Django 5.1.2 on 2025-03-18 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0010_remove_basketitem_quantity_basketitem_productid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paymentMethod',
            field=models.CharField(choices=[('credit', 'Credit card'), ('debit', 'Debit card'), ('paypal', 'Paypal')], default='credit', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('delivered', 'Delivered'), ('route', 'On Route'), ('refunded', 'Refunded'), ('pending', 'Order Pending')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='productcategories',
            name='categories',
            field=models.CharField(choices=[('summer', 'Summer Hats'), ('themed', 'Themed Hats'), ('occasional', 'Occasional Hats'), ('seasonal', 'Seasonal Hats'), ('cozy', 'Cozy & Comfortable Hats')], default='hats', max_length=50),
        ),
    ]
