# Generated by Django 5.1.2 on 2025-03-22 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0010_discount_alter_order_paymentmethod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paymentMethod',
            field=models.CharField(choices=[('paypal', 'Paypal'), ('debit', 'Debit card'), ('credit', 'Credit card')], default='credit', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('delivered', 'Delivered'), ('route', 'On Route'), ('pending', 'Order Pending'), ('refunded', 'Refunded')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='productcategories',
            name='categories',
            field=models.CharField(choices=[('seasonal', 'Seasonal Hats'), ('themed', 'Themed Hats'), ('occasional', 'Occasional Hats'), ('cozy', 'Cozy & Comfortable Hats'), ('summer', 'Summer Hats')], default='hats', max_length=50),
        ),
    ]
