# Generated by Django 5.1.2 on 2025-03-16 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0011_remove_wishlistitem_basketid_wishlistitem_wishlistid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paymentMethod',
            field=models.CharField(choices=[('paypal', 'Paypal'), ('credit', 'Credit card'), ('debit', 'Debit card')], default='credit', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('delivered', 'Delivered'), ('route', 'On Route'), ('pending', 'Order Pending'), ('refunded', 'Refunded')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='productcategories',
            name='categories',
            field=models.CharField(choices=[('occasional', 'Occasional Hats'), ('themed', 'Themed Hats'), ('cozy', 'Cozy & Comfortable Hats'), ('summer', 'Summer Hats'), ('seasonal', 'Seasonal Hats')], default='hats', max_length=50),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='wishlistID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishListID', to='ecommerceapp.wishlists'),
        ),
    ]
