# Generated by Django 5.1.2 on 2025-03-20 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0011_alter_order_paymentmethod_alter_order_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketitem',
            name='productID',
        ),
        migrations.AddField(
            model_name='basketitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='basketitem',
            name='basketID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basketitem', to='ecommerceapp.basket'),
        ),
        migrations.AlterField(
            model_name='basketitem',
            name='variantID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basketitem', to='ecommerceapp.productvariant'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paymentMethod',
            field=models.CharField(choices=[('debit', 'Debit card'), ('credit', 'Credit card'), ('paypal', 'Paypal')], default='credit', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('delivered', 'Delivered'), ('pending', 'Order Pending'), ('refunded', 'Refunded'), ('route', 'On Route')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='productcategories',
            name='categories',
            field=models.CharField(choices=[('cozy', 'Cozy & Comfortable Hats'), ('seasonal', 'Seasonal Hats'), ('summer', 'Summer Hats'), ('themed', 'Themed Hats'), ('occasional', 'Occasional Hats')], default='hats', max_length=50),
        ),
    ]
