# Generated by Django 5.1.2 on 2025-03-19 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0012_alter_order_paymentmethod_alter_order_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistitem',
            name='variantID',
        ),
        migrations.AlterField(
            model_name='order',
            name='paymentMethod',
            field=models.CharField(choices=[('debit', 'Debit card'), ('credit', 'Credit card'), ('paypal', 'Paypal')], default='credit', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('route', 'On Route'), ('delivered', 'Delivered'), ('pending', 'Order Pending'), ('refunded', 'Refunded')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='productcategories',
            name='categories',
            field=models.CharField(choices=[('cozy', 'Cozy & Comfortable Hats'), ('occasional', 'Occasional Hats'), ('seasonal', 'Seasonal Hats'), ('themed', 'Themed Hats'), ('summer', 'Summer Hats')], default='hats', max_length=50),
        ),
    ]
