# Generated by Django 5.1.2 on 2025-03-22 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0012_alter_order_paymentmethod_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paymentMethod',
            field=models.CharField(choices=[('debit', 'Debit card'), ('paypal', 'Paypal'), ('credit', 'Credit card')], default='credit', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Order Pending'), ('refunded', 'Refunded'), ('route', 'On Route'), ('delivered', 'Delivered')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='productcategories',
            name='categories',
            field=models.CharField(choices=[('seasonal', 'Seasonal Hats'), ('cozy', 'Cozy & Comfortable Hats'), ('summer', 'Summer Hats'), ('occasional', 'Occasional Hats'), ('themed', 'Themed Hats')], default='hats', max_length=50),
        ),
    ]
