# Generated by Django 5.1.2 on 2025-03-26 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0011_remove_wishlistitem_basketid_wishlistitem_wishlistid_and_more'),
        ('ecommerceapp', '0013_remove_wishlistitem_variantid_and_more'),
        ('ecommerceapp', '0014_alter_order_paymentmethod_alter_order_status_and_more'),
    ]

    operations = [
    ]
