# Generated by Django 5.1.2 on 2025-03-26 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0014_alter_order_paymentmethod_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paymentMethod',
            field=models.CharField(choices=[('credit', 'Credit card'), ('debit', 'Debit card'), ('paypal', 'Paypal')], default='credit', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('route', 'On Route'), ('delivered', 'Delivered'), ('refunded', 'Refunded'), ('pending', 'Order Pending')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='productcategories',
            name='categories',
            field=models.CharField(choices=[('occasional', 'Occasional Hats'), ('seasonal', 'Seasonal Hats'), ('themed', 'Themed Hats'), ('summer', 'Summer Hats'), ('cozy', 'Cozy & Comfortable Hats')], default='hats', max_length=50),
        ),
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to='ecommerceapp.product')),
                ('wishlistID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishListID', to='ecommerceapp.wishlists')),
            ],
        ),
    ]
