# Generated by Django 5.1.2 on 2024-11-14 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderDate', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('delivered', 'Delivered'), ('refunded', 'Refunded'), ('pending', 'Order Pending'), ('route', 'On Route')], default='pending', max_length=50)),
                ('totalAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paymentMethod', models.CharField(max_length=50)),
                ('trackingInfo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=120)),
                ('password', models.CharField(max_length=200)),
                ('phoneNumber', models.IntegerField()),
                ('permissions', models.CharField(choices=[('customer', 'Customer'), ('admin', 'Admin-User')], default='customer', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(choices=[('hats', 'Hats'), ('sunglasses', 'Sunglasses')], default='hats', max_length=50)),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='ecommerceapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50)),
                ('colour', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField()),
                ('stocklevel', models.PositiveIntegerField()),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productvariant', to='ecommerceapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('priceAtPurchase', models.DecimalField(decimal_places=2, max_digits=10)),
                ('orderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderitem', to='ecommerceapp.order')),
                ('variantID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderitem', to='ecommerceapp.productvariant')),
            ],
        ),
        migrations.CreateModel(
            name='ImagePath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productVariantID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagepath', to='ecommerceapp.productvariant')),
            ],
        ),
        migrations.CreateModel(
            name='BasketItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('basketID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basketitem', to='ecommerceapp.basket')),
                ('variantID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basketitem', to='ecommerceapp.productvariant')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('reviewDate', models.DateTimeField(auto_now_add=True)),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='ecommerceapp.product')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='ecommerceapp.user'),
        ),
        migrations.AddField(
            model_name='basket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket', to='ecommerceapp.user'),
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('houseNumber', models.IntegerField()),
                ('street', models.CharField(max_length=50)),
                ('postcode', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=10)),
                ('apartmentNumber', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='useraddress', to='ecommerceapp.user')),
            ],
        ),
    ]
