# Generated by Django 5.1.2 on 2024-11-19 15:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0003_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('delivered', 'Delivered'), ('pending', 'Order Pending'), ('refunded', 'Refunded'), ('route', 'On Route')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='permissions',
            field=models.CharField(choices=[('admin', 'Admin-User'), ('customer', 'Customer')], default='customer', max_length=50),
        ),
    ]
