# Generated by Django 5.1.2 on 2024-12-07 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0003_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('refunded', 'Refunded'), ('pending', 'Order Pending'), ('delivered', 'Delivered'), ('route', 'On Route')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='productcategories',
            name='categories',
            field=models.CharField(choices=[('occasional', 'Occasional Hats'), ('cozy', 'Cozy & Comfortable Hats'), ('summer', 'Summer Hats'), ('seasonal', 'Seasonal Hats'), ('themed', 'Themed Hats')], default='hats', max_length=50),
        ),
    ]
