# Generated by Django 5.1.2 on 2024-11-20 11:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0004_alter_order_status_alter_review_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='user',
            new_name='userID',
        ),
        migrations.RenameField(
            model_name='useraddress',
            old_name='user',
            new_name='userID',
        ),
        migrations.AlterField(
            model_name='basketitem',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='paymentMethod',
            field=models.CharField(choices=[('credit', 'Credit card'), ('paypal', 'Paypal'), ('debit', 'Debit card')], default='credit', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('route', 'On Route'), ('pending', 'Order Pending'), ('delivered', 'Delivered'), ('refunded', 'Refunded')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='permissions',
            field=models.CharField(choices=[('customer', 'Customer'), ('admin', 'Admin-User')], default='customer', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='phoneNumber',
            field=models.PositiveIntegerField(),
        ),
    ]
