# Generated by Django 5.1.2 on 2024-11-30 14:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0005_remove_basket_user_alter_order_userid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='availability',
        ),
        migrations.AddField(
            model_name='imagepath',
            name='imagepath',
            field=models.ImageField(blank=True, upload_to='uploads/product-images/'),
        ),
        migrations.AddField(
            model_name='imagepath',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('route', 'On Route'), ('delivered', 'Delivered'), ('refunded', 'Refunded'), ('pending', 'Order Pending')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='productcategories',
            name='categories',
            field=models.CharField(choices=[('hats', 'Hats'), ('sunglasses', 'Sunglasses')], default='hats', max_length=50),
        ),
    ]
