# Generated by Django 5.1.2 on 2024-11-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0005_remove_basket_user_alter_order_userid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagepath',
            name='imagepath',
            field=models.ImageField(blank=True, upload_to='productvariant'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('refunded', 'Refunded'), ('delivered', 'Delivered'), ('route', 'On Route'), ('pending', 'Order Pending')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='productcategories',
            name='categories',
            field=models.CharField(choices=[('hats', 'Hats'), ('sunglasses', 'Sunglasses')], default='hats', max_length=50),
        ),
    ]
