# Generated by Django 5.1.2 on 2024-11-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0005_remove_basket_user_alter_order_userid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagepath',
            name='imagepath',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Order Pending'), ('delivered', 'Delivered'), ('refunded', 'Refunded'), ('route', 'On Route')], default='pending', max_length=50),
        ),
    ]
