# Generated by Django 5.1.2 on 2024-12-01 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0006_remove_product_availability_imagepath_imagepath_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('refunded', 'Refunded'), ('route', 'On Route'), ('delivered', 'Delivered'), ('pending', 'Order Pending')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='productcategories',
            name='categories',
            field=models.CharField(choices=[('sunglasses', 'Sunglasses'), ('hats', 'Hats')], default='hats', max_length=50),
        ),
    ]
