# Generated by Django 5.1.2 on 2024-11-20 11:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0007_alter_order_paymentmethod_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paymentMethod',
            field=models.CharField(choices=[('debit', 'Debit card'), ('paypal', 'Paypal'), ('credit', 'Credit card')], default='credit', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('refunded', 'Refunded'), ('delivered', 'Delivered'), ('route', 'On Route'), ('pending', 'Order Pending')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='totalAmount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
