# Generated by Django 5.1.2 on 2024-12-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0007_alter_order_paymentmethod_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paymentMethod',
            field=models.CharField(choices=[('debit', 'Debit card'), ('credit', 'Credit card'), ('paypal', 'Paypal')], default='credit', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('refunded', 'Refunded'), ('delivered', 'Delivered'), ('route', 'On Route'), ('pending', 'Order Pending')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='productcategories',
            name='categories',
            field=models.CharField(choices=[('themed', 'Themed Hats'), ('seasonal', 'Seasonal Hats'), ('cozy', 'Cozy & Comfortable Hats'), ('summer', 'Summer Hats'), ('occasional', 'Occasional Hats')], default='hats', max_length=50),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='apartmentNumber',
            field=models.IntegerField(blank=True),
        ),
    ]
