# Generated by Django 5.1.2 on 2024-12-01 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0005_remove_basket_user_alter_order_userid_and_more'),
        ('ecommerceapp', '0008_alter_order_paymentmethod_alter_order_status_and_more'),
    ]

    operations = [
    ]
